import type { Config } from 'tailwindcss'

export default {
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  theme: {
    container: { center: true, padding: '1rem' },
    screens: {
      sm: '640px',
      md: '768px',
      lg: '1024px',
      xl: '1280px',
      '2xl': '1536px',
    },
    extend: {
      colors: {
        'bg-cool': 'var(--color-bg-cool)',
        'bg-warm': 'var(--color-bg-warm)',
        'bg-deep': 'var(--color-bg-deep)',
        'bg-mist': 'var(--color-bg-mist)',
        'text-primary': 'var(--color-text-primary)',
        'text-secondary': 'var(--color-text-secondary)',
        'text-muted': 'var(--color-text-muted)',
        'text-subtle': 'var(--color-text-subtle)',
        'text-on-deep': 'var(--color-text-on-deep)',
        clinical: {
          DEFAULT: 'var(--color-clinical)',
          soft: 'var(--color-clinical-soft)',
          deep: 'var(--color-clinical-deep)',
        },
        coaching: {
          DEFAULT: 'var(--color-coaching)',
          soft: 'var(--color-coaching-soft)',
          deep: 'var(--color-coaching-deep)',
        },
        cta: {
          DEFAULT: 'var(--color-cta)',
          hover: 'var(--color-cta-hover)',
          soft: 'var(--color-cta-soft)',
        },
        line: {
          DEFAULT: 'var(--color-line)',
          strong: 'var(--color-line-strong)',
        },
        'chart-fast': 'var(--color-chart-fast)',
        'chart-target': 'var(--color-chart-target)',
        'chart-progress': 'var(--color-chart-progress)',
      },
      fontFamily: {
        sans: ['Pretendard Variable', 'Inter', 'system-ui', 'sans-serif'],
        serif: ['Noto Serif KR', 'Georgia', 'serif'],
        mono: ['JetBrains Mono', 'monospace'],
      },
      fontSize: {
        'display-xl': ['64px', { lineHeight: '72px', letterSpacing: '-0.025em', fontWeight: '700' }],
        'display-lg': ['52px', { lineHeight: '60px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'heading-1': ['40px', { lineHeight: '48px', letterSpacing: '-0.015em', fontWeight: '600' }],
        'heading-2': ['32px', { lineHeight: '40px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'heading-3': ['24px', { lineHeight: '32px', letterSpacing: '-0.005em', fontWeight: '600' }],
        'heading-4': ['20px', { lineHeight: '28px', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '30px' }],
        'body': ['16px', { lineHeight: '26px' }],
        'body-sm': ['14px', { lineHeight: '22px' }],
        'caption': ['13px', { lineHeight: '20px', letterSpacing: '0.005em' }],
        'label': ['12px', { lineHeight: '18px', letterSpacing: '0.04em', fontWeight: '500' }],
        'quote-display': ['36px', { lineHeight: '48px', letterSpacing: '-0.005em' }],
        'data-mono': ['14px', { lineHeight: '22px', fontWeight: '500' }],
      },
      spacing: {
        '0': 'var(--space-0)',
        '1': 'var(--space-1)',
        '2': 'var(--space-2)',
        '3': 'var(--space-3)',
        '4': 'var(--space-4)',
        '5': 'var(--space-5)',
        '6': 'var(--space-6)',
        '8': 'var(--space-8)',
        '10': 'var(--space-10)',
        '12': 'var(--space-12)',
        '16': 'var(--space-16)',
        '20': 'var(--space-20)',
        '24': 'var(--space-24)',
        '32': 'var(--space-32)',
        '40': 'var(--space-40)',
      },
      borderRadius: {
        sm: '6px',
        md: '12px',
        lg: '16px',
        xl: '24px',
        '2xl': '32px',
      },
      boxShadow: {
        xs: 'var(--shadow-xs)',
        sm: 'var(--shadow-sm)',
        md: 'var(--shadow-md)',
        lg: 'var(--shadow-lg)',
        xl: 'var(--shadow-xl)',
        'glow-clinical': 'var(--shadow-glow-clinical)',
        'glow-coaching': 'var(--shadow-glow-coaching)',
      },
      backgroundImage: {
        'grad-hero': 'var(--grad-hero)',
        'grad-solution': 'var(--grad-solution)',
        'grad-airpods-demo': 'var(--grad-airpods-demo)',
        'grad-cta': 'var(--grad-cta)',
        'grad-final-cta': 'var(--grad-final-cta)',
      },
      maxWidth: {
        container: '1200px',
        narrow: '880px',
        'prose-narrow': '680px',
      },
      transitionTimingFunction: {
        reveal: 'cubic-bezier(0.16, 1, 0.3, 1)',
      },
    },
  },
  plugins: [],
} satisfies Config
